package pck;

import contabancaria.ContaCorrente;
import contabancaria.ContaPoupanca;
import contabancaria.Executavel2;

/**
 *
 * @author Grácio Macuácua
 */
public class CriarConta extends javax.swing.JPanel {

    /**
     * Creates new form CriarConta
     */
    public CriarConta() {
        initComponents();
        btnGroup.add(radio1);
        btnGroup.add(radio2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        colorPanel2 = new pck.ColorPanel();
        lblIcone1 = new javax.swing.JLabel();
        lblIcone2 = new javax.swing.JLabel();
        lblIcone4 = new javax.swing.JLabel();
        lblIcone3 = new javax.swing.JLabel();
        lblIcone5 = new javax.swing.JLabel();
        lblIcone6 = new javax.swing.JLabel();
        lblIcone7 = new javax.swing.JLabel();
        lblIcone8 = new javax.swing.JLabel();
        colorPanel3 = new pck.ColorPanel();
        icone = new javax.swing.JLabel();
        colorPanel4 = new pck.ColorPanel();
        lblIcone9 = new javax.swing.JLabel();
        radio1 = new javax.swing.JRadioButton();
        radio2 = new javax.swing.JRadioButton();
        lblIcone10 = new javax.swing.JLabel();
        txtNumeroConta = new javax.swing.JTextField();
        lblIcone11 = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        btnGuardar = new com.k33ptoo.components.KButton();
        btnCancelar = new com.k33ptoo.components.KButton();

        setOpaque(false);

        colorPanel2.setkEndColor(new java.awt.Color(102, 255, 255));
        colorPanel2.setkStartColor(new java.awt.Color(0, 153, 153));
        colorPanel2.setPreferredSize(new java.awt.Dimension(342, 141));
        colorPanel2.setRaioX(30);
        colorPanel2.setRaioY(30);

        lblIcone1.setBackground(new java.awt.Color(255, 255, 255));
        lblIcone1.setOpaque(true);

        lblIcone2.setBackground(new java.awt.Color(255, 255, 255));
        lblIcone2.setOpaque(true);

        lblIcone4.setBackground(new java.awt.Color(255, 255, 255));
        lblIcone4.setOpaque(true);

        lblIcone3.setBackground(new java.awt.Color(255, 255, 255));
        lblIcone3.setOpaque(true);

        lblIcone5.setBackground(new java.awt.Color(255, 255, 255));
        lblIcone5.setOpaque(true);

        lblIcone6.setBackground(new java.awt.Color(255, 255, 255));
        lblIcone6.setOpaque(true);

        lblIcone7.setBackground(new java.awt.Color(255, 255, 255));
        lblIcone7.setOpaque(true);

        lblIcone8.setBackground(new java.awt.Color(255, 255, 255));
        lblIcone8.setOpaque(true);

        javax.swing.GroupLayout colorPanel2Layout = new javax.swing.GroupLayout(colorPanel2);
        colorPanel2.setLayout(colorPanel2Layout);
        colorPanel2Layout.setHorizontalGroup(
            colorPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, colorPanel2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(colorPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIcone4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIcone3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIcone2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIcone1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(colorPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIcone8, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIcone7, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIcone6, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIcone5, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
        colorPanel2Layout.setVerticalGroup(
            colorPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, colorPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(colorPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(colorPanel2Layout.createSequentialGroup()
                        .addComponent(lblIcone5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIcone6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIcone7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIcone8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(colorPanel2Layout.createSequentialGroup()
                        .addComponent(lblIcone1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIcone2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIcone3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIcone4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );

        colorPanel3.setkEndColor(new java.awt.Color(102, 255, 255));
        colorPanel3.setkStartColor(new java.awt.Color(0, 153, 153));
        colorPanel3.setRaioX(800);
        colorPanel3.setRaioY(500);

        icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/adduser.png"))); // NOI18N

        javax.swing.GroupLayout colorPanel3Layout = new javax.swing.GroupLayout(colorPanel3);
        colorPanel3.setLayout(colorPanel3Layout);
        colorPanel3Layout.setHorizontalGroup(
            colorPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(icone)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        colorPanel3Layout.setVerticalGroup(
            colorPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(icone)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        colorPanel4.setkEndColor(new java.awt.Color(102, 255, 255));
        colorPanel4.setkStartColor(new java.awt.Color(0, 153, 153));
        colorPanel4.setRaioX(30);
        colorPanel4.setRaioY(30);

        lblIcone9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblIcone9.setForeground(new java.awt.Color(255, 255, 255));
        lblIcone9.setText("Selecione o tipo de conta");

        radio1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radio1.setForeground(new java.awt.Color(255, 255, 255));
        radio1.setText("Conta Corrente");

        radio2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radio2.setForeground(new java.awt.Color(255, 255, 255));
        radio2.setText("Conta Poupança");

        lblIcone10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblIcone10.setForeground(new java.awt.Color(255, 255, 255));
        lblIcone10.setText("Introduza o número da conta");

        txtNumeroConta.setBackground(new java.awt.Color(255, 255, 255));
        txtNumeroConta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNumeroConta.setForeground(new java.awt.Color(102, 102, 102));
        txtNumeroConta.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 153)));
        txtNumeroConta.setCaretColor(new java.awt.Color(51, 51, 51));

        lblIcone11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblIcone11.setForeground(new java.awt.Color(255, 255, 255));
        lblIcone11.setText("Introduza o saldo inicial");

        txtSaldo.setBackground(new java.awt.Color(255, 255, 255));
        txtSaldo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSaldo.setForeground(new java.awt.Color(102, 102, 102));
        txtSaldo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 153)));
        txtSaldo.setCaretColor(new java.awt.Color(51, 51, 51));

        btnGuardar.setText("Guardar Registo");
        btnGuardar.setkAllowTab(true);
        btnGuardar.setkBackGroundColor(new java.awt.Color(0, 153, 153));
        btnGuardar.setkBorderRadius(0);
        btnGuardar.setkEndColor(new java.awt.Color(0, 153, 153));
        btnGuardar.setkHoverEndColor(new java.awt.Color(0, 153, 153));
        btnGuardar.setkHoverForeGround(new java.awt.Color(204, 204, 204));
        btnGuardar.setkHoverStartColor(new java.awt.Color(0, 153, 153));
        btnGuardar.setkSelectedColor(new java.awt.Color(0, 153, 153));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar Registo");
        btnCancelar.setkAllowTab(true);
        btnCancelar.setkBackGroundColor(new java.awt.Color(0, 153, 153));
        btnCancelar.setkBorderRadius(0);
        btnCancelar.setkEndColor(new java.awt.Color(0, 153, 153));
        btnCancelar.setkHoverEndColor(new java.awt.Color(0, 153, 153));
        btnCancelar.setkHoverForeGround(new java.awt.Color(204, 204, 204));
        btnCancelar.setkHoverStartColor(new java.awt.Color(0, 153, 153));
        btnCancelar.setkSelectedColor(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout colorPanel4Layout = new javax.swing.GroupLayout(colorPanel4);
        colorPanel4.setLayout(colorPanel4Layout);
        colorPanel4Layout.setHorizontalGroup(
            colorPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(colorPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, colorPanel4Layout.createSequentialGroup()
                        .addGroup(colorPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(colorPanel4Layout.createSequentialGroup()
                                .addComponent(txtNumeroConta)
                                .addGap(102, 102, 102))
                            .addGroup(colorPanel4Layout.createSequentialGroup()
                                .addGroup(colorPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIcone11, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)))
                        .addGroup(colorPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(colorPanel4Layout.createSequentialGroup()
                        .addGroup(colorPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIcone9, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIcone10, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(colorPanel4Layout.createSequentialGroup()
                        .addComponent(radio1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radio2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))))
        );
        colorPanel4Layout.setVerticalGroup(
            colorPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblIcone9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(colorPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radio2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(lblIcone10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(colorPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroConta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblIcone11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(colorPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(colorPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(colorPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(colorPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(colorPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(colorPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(colorPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(radio1.isSelected()) {
            ContaCorrente cc = new ContaCorrente(Integer.parseInt(txtNumeroConta.getText()), Double.parseDouble(txtSaldo.getText()));
            Executavel2.banco.inserir(cc);
        } else if(radio2.isSelected()) {
            ContaPoupanca cp = new ContaPoupanca(Integer.parseInt(txtNumeroConta.getText()), Double.parseDouble(txtSaldo.getText()));
            Executavel2.banco.inserir(cp);
        }
                
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnCancelar;
    private javax.swing.ButtonGroup btnGroup;
    private com.k33ptoo.components.KButton btnGuardar;
    private pck.ColorPanel colorPanel2;
    private pck.ColorPanel colorPanel3;
    private pck.ColorPanel colorPanel4;
    private javax.swing.JLabel icone;
    private javax.swing.JLabel lblIcone1;
    private javax.swing.JLabel lblIcone10;
    private javax.swing.JLabel lblIcone11;
    private javax.swing.JLabel lblIcone2;
    private javax.swing.JLabel lblIcone3;
    private javax.swing.JLabel lblIcone4;
    private javax.swing.JLabel lblIcone5;
    private javax.swing.JLabel lblIcone6;
    private javax.swing.JLabel lblIcone7;
    private javax.swing.JLabel lblIcone8;
    private javax.swing.JLabel lblIcone9;
    private javax.swing.JRadioButton radio1;
    private javax.swing.JRadioButton radio2;
    private javax.swing.JTextField txtNumeroConta;
    private javax.swing.JTextField txtSaldo;
    // End of variables declaration//GEN-END:variables
}
