package pck;

import contabancaria.ContaBancaria;
import contabancaria.Executavel2;
import static contabancaria.Executavel2.banco;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Grácio Macuácua
 */
public class MenuOptions extends javax.swing.JPanel {

    /**
     * Creates new form MenuOptions
     */
    public MenuOptions() {        
        initComponents();
        setOpaque(false);
        listMenu1.setOpaque(false);
                
        listMenu1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                String input;
                switch (listMenu1.getSelectedIndex()) {
                    case 1:
                        reset(panel);
                        panel.add(new CriarConta());
                        break;
                    case 2:
                        input = JOptionPane.showInputDialog(null, "<html>Introduza o número<br> de conta a selecionar</html>");
                        if(input != null && !input.isBlank()) {
                            ContaBancaria cb = banco.procurarConta(Integer.parseInt(input));
                            if(cb != null) {
                                reset(panel2);
                                panel2.add(new SubMenu(cb));                                
                            }else {
                                JOptionPane.showMessageDialog(null, "A conta não existe!");
                            }
                        }                                           
                        break;
                    case 3:                        
                        input = JOptionPane.showInputDialog(null, "<html>Introduza o número da <br>conta que deseja remover</html>");
                        if(null != input && !input.isBlank()) {                       
                            contabancaria.ContaBancaria cb = Executavel2.banco.procurarConta(Integer.parseInt(input));
                            if(null != cb) {
                                Executavel2.banco.remover(cb);
                                JOptionPane.showMessageDialog(null, "Conta removida com sucesso!", "Confirmação", JOptionPane.INFORMATION_MESSAGE);
                            }else
                                JOptionPane.showMessageDialog(null, "A conta não existe!");
                        }
                        break;
                    case 6:
                        reset(panel);
                        panel.add(new Relatorio());
                        break;
                    case 7:
                        if(0 == JOptionPane.showConfirmDialog(null, "Deseja finalizar o programa?", "Atenção", JOptionPane.YES_NO_OPTION))
                            System.exit(0);
                        break;
                    default:
                        break;
                }
                
            }
            
        });
    }
    
    /**
     * 
     * @param panel o painel a ser redefinido
     */
    public static void reset(JPanel panel){
        panel.removeAll();
        panel.repaint();
        panel.revalidate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        colorPanel1 = new pck.ColorPanel();
        jLabel1 = new javax.swing.JLabel();
        listMenu1 = new pck.ListMenu();

        colorPanel1.setkEndColor(new java.awt.Color(51, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Aplicação");

        listMenu1.setOpaque(false);

        javax.swing.GroupLayout colorPanel1Layout = new javax.swing.GroupLayout(colorPanel1);
        colorPanel1.setLayout(colorPanel1Layout);
        colorPanel1Layout.setHorizontalGroup(
            colorPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(listMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        colorPanel1Layout.setVerticalGroup(
            colorPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, colorPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(listMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(colorPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(colorPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
            
    @Override
    protected void paintChildren(Graphics g) {
        Graphics2D g2 = (Graphics2D) g;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        GradientPaint gp = new GradientPaint(0, 0, colorPanel1.getkEndColor(), 0, getHeight(), colorPanel1.getkStartColor());
        g2.setPaint(gp);
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        g2.fillRect(getWidth()-20, 0, getWidth(), getHeight());
        super.paintChildren(g);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pck.ColorPanel colorPanel1;
    private javax.swing.JLabel jLabel1;
    private pck.ListMenu listMenu1;
    // End of variables declaration//GEN-END:variables
    public JPanel panel;
    public static JPanel panel2;
}
